"""【A】增加注册时间

Revision ID: 11053e498645
Revises: a10052cd5a4a
Create Date: 2019-05-21 17:55:17.727478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11053e498645'
down_revision = 'a10052cd5a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('register_time')

    # ### end Alembic commands ###
