FLASK_DEBUG = True
FLASK_SERVER_NAME = "http://localhost:5000"

SQLALCHEMY_DATABASE_URI = "sqlite:///db.sqlite"
SQLALCHEMY_TRACK_MODIFICATIONS = False

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

# 证书路劲
CERT_CRT_PATH = ""
CERT_KEY_PATH = ""
